### ISSUE TITLE
메인 페이지 제작

### ISSUE THREAD

**Issue by YOOGOMJA** [DSC-Sahmyook/Sejul-client#10]
메인 페이지 제작이 필요합니다
제작 중 필요한 항목들은 컴포넌트로 별도 분리되어야 합니다
관련 API가 완성되는 대로 댓글로 달릴 예정입니다

# 페이지 제작 

- [x] 메인 페이지 제작 

# 컴포넌트 제작 

- [ ] 글 컴포넌트 
- [x] 해시태그 박스 
- [x] 사용자 박스 

## 유의 사항 

사용자 박스는 세로와 가로 모두 지원해야합니다.

**Comment by YOOGOMJA** [comment]
# 가장 글이 많은 해시태그
/api/analytics/hashtag/hottest

# 최근 작성글 
/api/analytics/summary/recent

# 활동이 많은 유저
/api/analytics/user/featured

**Comment by blair06** [comment]
최근 작성된글, 해시태그, 활발한 유저 셋다 링크 연결해야할까요? @YOOGOMJA

**Comment by YOOGOMJA** [comment]
- [ ] 메인 배너 꼼수부리지 마세여 
- [ ] 글 카드 작성 시간이랑, 요약 시간 보여주세여 
- [ ] 해시태그 텍스트 부분 별도 컴포넌트로 빼세여
